# Homebrew Cask for Konjugate's own tap (zenineasa/homebrew-konjugate) -- generated by
# scripts/generateHomebrewCask.mjs --tap from release v1.1.8, and committed to the tap
# repository by release.yml's homebrewTapRelease job. Don't edit it by hand: the next release
# overwrites it.
#
# Covers both macOS (DMG/.app) and Linux (AppImage, via the app_image artifact stanza) in one
# cask, following the same on_macos/on_linux pattern real casks like cursor.rb and warp.rb use --
# Homebrew Cask has real, current Linux support, not just macOS, confirmed against those live casks.

cask "konjugate" do
  arch arm: "arm64", intel: "x64"

  version "1.1.8"
  sha256 arm:   "d37a523151b9ef57dd2c932b48d53a3b1113deb3f21c1d2bb85f94d4f59d49c9",
         intel: "007807a02b7550d04accec2875edcec5b998fb1184e9506c8b283dbda1ce4ef7",
         x86_64_linux: "b38a61e7d1e10f4d4df082a1fee68b05e049132b167ef42474eede62c58b2f7e"

  on_macos do
    url "https://github.com/zenineasa/Konjugate/releases/download/v#{version}/Konjugate-#{version}-#{arch}.dmg",
        verified: "github.com/zenineasa/Konjugate/"
    auto_updates true
    depends_on macos: :big_sur

    app "Konjugate.app"

    # Homebrew marks everything it installs as downloaded-from-the-internet, and an app that is
    # neither signed nor notarized then fails Gatekeeper's check with "Konjugate is damaged". This
    # clears that mark, which is what makes a plain `brew install --cask` give an app that opens.
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{appdir}/Konjugate.app"]
    end

    caveats <<~EOS
      Konjugate is not code-signed or notarized yet (an active choice while the project is in
      beta). To let it open, this cask removes macOS's quarantine flag from Konjugate.app after
      installing it -- which also means macOS has not checked the app. Only install it if you
      trust this tap and the project.
    EOS

    zap trash: [
      "~/Library/Application Support/Konjugate",
      "~/Library/Preferences/com.konjugate.plist",
      "~/Library/Saved Application State/com.konjugate.savedState",
    ]
  end

  on_linux do
    url "https://github.com/zenineasa/Konjugate/releases/download/v#{version}/Konjugate-#{version}-x86_64.AppImage",
        verified: "github.com/zenineasa/Konjugate/"
    depends_on arch: :x86_64

    app_image "Konjugate-1.1.8-x86_64.AppImage", target: "Konjugate.AppImage"
  end

  name "Konjugate"
  desc "Graph-native simulation engine for engineering and digital twins"
  homepage "https://github.com/zenineasa/Konjugate"

  livecheck do
    url :url
    strategy :github_latest
  end
end
