# Homebrew Cask for Konjugate's own tap (zenineasa/homebrew-konjugate) -- generated by
# scripts/generateHomebrewCask.mjs --tap from release v1.1.11, and committed to the tap
# repository by release.yml's homebrewTapRelease job. Don't edit it by hand: the next release
# overwrites it.
#
# Covers both macOS (DMG/.app) and Linux (AppImage, via the app_image artifact stanza) in one
# cask, following the same on_macos/on_linux pattern real casks like cursor.rb and warp.rb use --
# Homebrew Cask has real, current Linux support, not just macOS, confirmed against those live casks.

cask "konjugate" do
  arch arm: "arm64", intel: "x64"

  version "1.1.11"
  sha256 arm:   "69227a00ee2f4824e21434f6e75c23a044af87e09214aced3048458d0565cb3c",
         intel: "9857f85476db93a06def182fefa0660cf582bcf4c7f7c34eca6aa392309c1ed3",
         x86_64_linux: "edee8404cfd6008e77525aa39b3b5c5d43b51ef62cf3284f0919154903fa07b6"

  on_macos do
    url "https://github.com/zenineasa/Konjugate/releases/download/v#{version}/Konjugate-#{version}-#{arch}.dmg",
        verified: "github.com/zenineasa/Konjugate/"
    depends_on macos: :big_sur

    app "Konjugate.app"

    # Homebrew marks everything it installs as downloaded-from-the-internet, and an app that is
    # neither signed nor notarized then fails Gatekeeper's check with "Konjugate is damaged". This
    # clears that mark, which is what makes a plain `brew install --cask` give an app that opens.
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{appdir}/Konjugate.app"]
    end

    caveats <<~EOS
      Konjugate is not code-signed or notarized yet (an active choice while the project is in
      beta). To let it open, this cask removes macOS's quarantine flag from Konjugate.app after
      installing it -- which also means macOS has not checked the app. Only install it if you
      trust this tap and the project.
    EOS

    zap trash: [
      "~/Library/Application Support/Konjugate",
      "~/Library/Preferences/com.konjugate.plist",
      "~/Library/Saved Application State/com.konjugate.savedState",
    ]
  end

  on_linux do
    url "https://github.com/zenineasa/Konjugate/releases/download/v#{version}/Konjugate-#{version}-x86_64.AppImage",
        verified: "github.com/zenineasa/Konjugate/"
    depends_on arch: :x86_64

    app_image "Konjugate-1.1.11-x86_64.AppImage", target: "Konjugate.AppImage"
  end

  name "Konjugate"
  desc "Graph-native simulation engine for engineering and digital twins"
  homepage "https://github.com/zenineasa/Konjugate"

  livecheck do
    url :url
    strategy :github_latest
  end
end
