# Homebrew Cask for Konjugate's own tap (zenineasa/homebrew-konjugate) -- generated by
# scripts/generateHomebrewCask.mjs --tap from release v1.1.7, and committed to the tap
# repository by release.yml's homebrewTapRelease job. Don't edit it by hand: the next release
# overwrites it.
#
# Covers both macOS (DMG/.app) and Linux (AppImage, via the app_image artifact stanza) in one
# cask, following the same on_macos/on_linux pattern real casks like cursor.rb and warp.rb use --
# Homebrew Cask has real, current Linux support, not just macOS, confirmed against those live casks.

cask "konjugate" do
  arch arm: "arm64", intel: "x64"

  version "1.1.7"
  sha256 arm:   "e3be9d6037e01fd3d2b2a4a247e2b6d66c966b8acac4bae075cc217a9936ba05",
         intel: "503f102433545bd83d1392c31370b5d26fd8b2669e44bbd6966c4b142a2bcea4",
         x86_64_linux: "8847bea841eb00880da0925af51551d234857c7b6fd08b8eb46c5627392a0003"

  on_macos do
    url "https://github.com/zenineasa/Konjugate/releases/download/v#{version}/Konjugate-#{version}-#{arch}.dmg",
        verified: "github.com/zenineasa/Konjugate/"
    auto_updates true
    depends_on macos: :big_sur

    app "Konjugate.app"

    # Homebrew marks everything it installs as downloaded-from-the-internet, and an app that is
    # neither signed nor notarized then fails Gatekeeper's check with "Konjugate is damaged". This
    # clears that mark, which is what makes a plain `brew install --cask` give an app that opens.
    postflight do
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{appdir}/Konjugate.app"]
    end

    caveats <<~EOS
      Konjugate is not code-signed or notarized yet (an active choice while the project is in
      beta). To let it open, this cask removes macOS's quarantine flag from Konjugate.app after
      installing it -- which also means macOS has not checked the app. Only install it if you
      trust this tap and the project.
    EOS

    zap trash: [
      "~/Library/Application Support/Konjugate",
      "~/Library/Preferences/com.konjugate.plist",
      "~/Library/Saved Application State/com.konjugate.savedState",
    ]
  end

  on_linux do
    url "https://github.com/zenineasa/Konjugate/releases/download/v#{version}/Konjugate-#{version}-x86_64.AppImage",
        verified: "github.com/zenineasa/Konjugate/"
    depends_on arch: :x86_64

    app_image "Konjugate-1.1.7-x86_64.AppImage", target: "Konjugate.AppImage"
  end

  name "Konjugate"
  desc "Graph-native simulation engine for engineering and digital twins"
  homepage "https://github.com/zenineasa/Konjugate"

  livecheck do
    url :url
    strategy :github_latest
  end
end
